export const GET_ALL_PROPERTIES = "GET_ALL_PROPERTIES";
export const GET_SPECIFIC_PROPERTIE = "GET_SPECIFIC_PROPERTIE";
export const CREATE_PROPERTY = "CREATE_PROPERTY";
export const CREATE_NEW_USER = " CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_ERROR = "GET_ERROR";
